import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ToastProvider } from '@/components/providers/react-toastify'
import { GlobalProvider } from '@/Provider'



export const metadata = {
  title: 'Learning Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ToastProvider/>
          <GlobalProvider>
            {children}
          </GlobalProvider>
        </body>
      </html>
    </ClerkProvider>

  )
}
